
test: *.cpp *.h ../*.cpp ../*.h
	g++ -Wall -O3 test_main.cpp test_suffixnodestoredisk.cpp ../SuffixNode.cpp ../tialloc/tialloc.cpp ../SuffixNodeStoreDisk.cpp -o test -I.. -I../tialloc
clean:
	rm test
